### ISSUE TITLE
Passing values shouldn't treat value property as value

### ISSUE THREAD

**Issue by leesiongchan** [foxhound87/mobx-ajv-form#103]
``` javascript
const fields = [
  'inventoryLevel.value',
];

const values = {
  inventoryLevel: {
    value: 2,
  },
};

const form = new Form({ fields, values });

console.log(form.$('inventoryLevel')); // Output: 2
console.log(form.$('inventoryLevel.value')); // Error
```

**Comment by foxhound87** [comment]
You encounter this because `value` is recognized as a special word as well as `label` or other props. Maybe a solution can be to use a special names for the props, something like `$value`, `$label`, etc...

So, for example, instead doing this:

``` javascript
const fields = [{
  name: 'city',
  label: 'City',
  value: 'New York'
}];
```

we should do this:

``` javascript
const fields = [{
  $name: 'city',
  $label: 'City',
  $value: 'New York'
}];
```

or

``` javascript
const fields = {
  username: {
    $label: 'Username',
  },
  password: {
    $label: 'Password',
  }
};
```

Obviously, this will break the data structures we already defined.

what do you think?

**Comment by leesiongchan** [comment]
Yea, for now I will just use the method you suggested, but shouldn't it be ignoring special words while using separated properties?

**Comment by foxhound87** [comment]
This commit should fix the issue: https://github.com/foxhound87/mobx-react-form/commit/e7bb7a798fe7ac89e14bcbe74b23128642a0922b

But `fields` is yet a reserved word, it is required, all other props can be used as field name.

**Comment by leesiongchan** [comment]
@foxhound87 The fix doesn't fix the nested property, for example.

```javascript
const fields = [
  'inventoryLevel.value',
  'addOns[].inventoryLevel.value',
];

const values = {
  addOns: [{
    inventoryLevel: {
      value: 3,
    },
  }],
  inventoryLevel: {
    value: 2,
  },
};
```

**Comment by foxhound87** [comment]
I still have not found a proper solution for this issue on nested fields

**Comment by foxhound87** [comment]
Using the `$` as prop prefix will fix this issue, but I think we should deprecate the `unified properties` on the long term, if we remove them the code will be better (no more confusion on syntax to use and the build will be smaller).  Using the `separated properties` is more flexible I think. I'm also having other issues on managing the state of the `unified properties`, additional code should be added to fix nested fields props when are updated, and it seems a bit tricky.

**Comment by foxhound87** [comment]
Should work now. 

I made more tests and I think I will not remove the `unified properties` anymore.
The code is deeply glued to both styles and would be a pain to rewrite all.
