### ISSUE TITLE
.set() array as value without nested fields not working

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#251]
Case (unified properties, don't mind the field name, I'm still struggling with making things work):

```
  role_id: {
    label: 'Role',
    rules: 'array',
    default: [],
    value: []
  },
```

Example of bad behaviour(s):

```
$r.form.$('role_id').set('value', [123])
$r.form.$('role_id').value # [123]

$r.form.$('role_id').set('value', [456])
$r.form.$('role_id').value # [456]

$r.form.$('role_id').set('value', [])
$r.form.$('role_id').value # [456] <- this should be [] instead

$r.form.$('role_id').update([]) # this also doesn't work
$r.form.set('value', { role_id: [] }) # still nope

$r.form.update({ role_id: [] }) 
$r.form.$('role_id').value # => "a"   <- wait, what
```

**Comment by d4rky-pl** [comment]
The problem is triggered inconsistently. Right now it seems that writing to value directly works as long as you don't use `update`. You cannot set the value with `form.set('value', { role_id: [123] })` so my workaround for now looks like this:

```
    this.form.set('value', {
      id:         user.id,
      email:      user.attributes.email,
      first_name: user.attributes.first_name,
      last_name:  user.attributes.last_name,
      permission: user.attributes.permission,
    })

    this.form.$('role_id').value = user.relationships.roles.data.map((role) => role.id)
```

**Comment by foxhound87** [comment]
What are you trying to achieve? The array elements should be single input fields? 

Right now the **unified mode** does not supports arrays correctly.

`$r.form.update({ role_id: [] })` should work using **separated mode** but you need to provide an `array structure`:

```
const fields = ['role_id[]'];

const values = { role_id: [] };

new Form({ fields, values });
``` 

Let me know if this works.

**Comment by foxhound87** [comment]
Eventually I can introduce a warning when using an **array** in conjunction with **unified** mode.

**Comment by d4rky-pl** [comment]
The array element should be a single input field - at first I wanted to use `<select/>` with `multiple`. Since it didn't work out OOTB I wrote a separate component that handles arrays by hand. I was trying to avoid nested fields because I know they require separated mode.

---

It seems that the unified mode should be actively discouraged at this point since it brings more issues than it solves problems - I'll rewrite all our forms so they use the other syntax. Too bad, because I really dislike the separated mode (I find it way less readable and much harder to compose) :)

**Comment by d4rky-pl** [comment]
> Let me know if this works.

Right now I'm crunching something else but I'll get back to this issue and ping you after I rewrite all of our forms to separated mode.

**Comment by foxhound87** [comment]
If you need to make a list of options consider using **options** prop as array on your select input. Then the field value will be just a single value, not an array. You can find examples on the demo repo.

**Comment by d4rky-pl** [comment]
@foxhound87 yeah, but I need `multiple` which means single value is not enough. Unless I'm not understanding something :)

**Comment by foxhound87** [comment]
@d4rky-pl sorry for the misunderstanding, you can find a demo example with multiple selected elements as well (it works also with empty array). See [here](https://github.com/foxhound87/mobx-react-form-demo/blob/76f3560fa35400a3ac17d1daff27919aba7c6b8d/src/forms/setup/companyWidgets.js#L31).

**Comment by foxhound87** [comment]
anyway, right now `.set('value', []);` works only if using **nested fields** and will set elements values on the nested fields (not the nested fields **container**). I will fix this.

In the meantime you can achieve it using `.sync([]);`

**Comment by foxhound87** [comment]
Now is fixed! Thank You

**Comment by d4rky-pl** [comment]
Thank YOU :) :+1:

**Comment by d4rky-pl** [comment]
I'm afraid it still doesn't work correctly.

Given:

```
const fields   = ['role_id[]'];
const labels   = {
  'role_id': 'Role'
}
const rules    = {
  'role_id': 'array'
};
const defaults = {
  'role_id': []
};
const values   = {
  'role_id[]': [],
};
```

I get this:

<img width="332" alt="screenshot 2017-04-05 08 53 22" src="https://cloud.githubusercontent.com/assets/284395/24693343/633ed440-19dd-11e7-92cc-60631f589fc5.png">

I might be doing something wrong though, at this point I'm very confused :)

**Comment by d4rky-pl** [comment]
All right, I dug deeper and I think the problem actually lies between the chair and the computer. This works:

```
$.form.update({ role_id: [1,2,3] })
$.form.update({ role_id: [] })
```

I realize that this is by design but it might be a good idea to write down an explanation of differences between `set(value)` / `set('value', value)`, `update()` and `sync()`. I'm afraid the documentation doesn't really differentiate between those three. I will be writing a blogpost this/next week about my  experiences and tips for mobx-react-form so if you'd be so kind to just give a short explanation here, I'll be very happy to include it and you could link the comment in FAQ :)

**Comment by foxhound87** [comment]
using array notation in `values` is not permitted:
```javascript
const values = {
  'role_id[]': [],
};
```

As said on the docs, the `set()` method is intended to be used for editing fields properties. When updating the nested fields values with `set()` it update only the existent fields, does not create new fields (like nested array fields elements), for this purpose `update()` is preferred.

`set(value)` is just an alias for `set('value', value)`

Also, as said in the docs `sync()` is an **Event Handler**, it accepts a `Proxy` object, eventually you can pass a value instead because some custom components are doing this.

**Comment by foxhound87** [comment]
Anyway thank you for expressing your experience with the package. It is good to understand a different point of view in order to make a better documentation. Let me know if you have more questions. Thanks!
